name: Section
version: 1.13.0
icon:
  name: layer-group
  set: "fontawesome|solid"
description: Section plugin provides a basic way to work with content sections.
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/section
bugs: https://github.com/flextype-plugins/section/issues
license: MIT

dependencies:
  flextype: 0.9.16
